sudo: required

dist: harmit/ci-image

notifications:
  email: false
  
before_install: 
  - if [ $TRAVIS_OS_NAME == "linux" ]; then 
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install: 
  - sudo opm install 1testrunner
  - sudo opm install 1bdd
  - sudo opm install

env:
  global:
  - CHANNEL=dev

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
jobs:
  include:
    - stage: Тестирование 
      script: opm test
    - stage: Сборка и публикация github & hub.oscript.io
      script: skip 
      before_deploy:
        - opm build ./
      deploy:
        - provider: releases
          api_key: "$GITHUB_OAUTH_TOKEN"
          file_glob: true
          file: gitsync*.ospx
          skip_cleanup: true
          on:
            branch: master
            tags: true
        - provider: script
          skip_cleanup: true
          script: opm push --token $GITHUB_OAUTH_TOKEN --channel dev --file ./gitsync-*.ospx;
          on:
            branch: develop
        - provider: script
          skip_cleanup: true
          script: opm push --token $GITHUB_OAUTH_TOKEN --channel stable --file ./gitsync-*.ospx;
          on:
            branch: master
            tags: true
