sudo: required

notifications:
  email: false
  
services:
  - docker

before_install:
  - docker pull harmit/ci-image

install: true

env:
  global:
  - CHANNEL=dev

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
jobs:
  include:
    - stage: Тестирование 
      script:  
      - docker version
      - docker run -it -v $(pwd):/work_dir harmit/ci-image -c 'll; cd /work_dir; opm install; opm install 1testrunner; sudo opm install 1bdd; opm test' | tee /tmp/test.log
      - grep -q ^PASS /tmp/test.log && ! grep -q ^FAIL /tmp/test.log
    - stage: Сборка и публикация github & hub.oscript.io
      script: skip 
      before_deploy:
        - opm build -mf build_packgedef ./
      deploy:
        - provider: releases
          api_key: "$GITHUB_OAUTH_TOKEN"
          file_glob: true
          file: gitsync*.ospx
          skip_cleanup: true
          on:
            branch: master
            tags: true
        - provider: script
          skip_cleanup: true
          script: opm push --token $GITHUB_OAUTH_TOKEN --channel dev --file ./gitsync-*.ospx;
          on:
            branch: develop
        - provider: script
          skip_cleanup: true
          script: opm push --token $GITHUB_OAUTH_TOKEN --channel stable --file ./gitsync-*.ospx;
          on:
            branch: master
            tags: true
