globals:
  storage-user: Администратор
  storage-pwd: ''
  git-path: git
  temp-dir: ""
  v8version: 8.3
  domain-email: localhost
  lic-try-count: 5
  plugins:
    enable:
      - test
      - test2
    disable:
      - test3
  plugins-config:
    git-url: git-url
    push: true
    pull: true
repositories:
   - name: <ТестовыйРепозиторий>
     disable: true
     storage-path: <КаталогХранилища1С_1>
     git-local-path: <ПутьКаталогаИсходников_1>		
   - name: <ТестовыйРепозиторий2>
     disable: true
     storage-path: <КаталогХранилища1С_2>
     git-local-path: <ПутьКаталогаИсходников_2>		
     storage-user: Администратор
     storage-pwd: ''
     git-path: git
     temp-dir: ""
     v8version: 8.3
     domain-email: localhost
     lic-try-count: 5
     plugins:
      enable:
        - test
        - test2
      disable:
        - test3
     plugins-config:
      git-url: git-url
      push: true
      pull: true
  

 